Overriding model.yaml nc=80 with nc=10
                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  2    115712  models.common.C3                        [128, 128, 2]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1     40455  models.yolo.Detect                      [10, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 270 layers, 7046599 parameters, 7046599 gradients, 15.9 GFLOPs
Transferred 343/349 items from yolov5s.pt
Scaled weight_decay = 0.0005
[34m[1moptimizer:[39m[22m SGD with parameter groups 57 weight, 60 weight (no decay), 60 bias
[34m[1mtrain: [39m[22mScanning '/opt/ml/detection/yolov5/dataset/labels/train.cache' images and labels... 4883 found, 0 missing, 0 empty, 1 corrupted: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4883/4883 [00:00<?, ?it/s]
[34m[1mtrain: [39m[22mWARNING: Ignoring corrupted image and/or label /opt/ml/detection/yolov5/dataset/images/train/4041.jpg: duplicate labels
[34m[1mval: [39m[22mScanning '/opt/ml/detection/yolov5/dataset/labels/train.cache' images and labels... 4883 found, 0 missing, 0 empty, 1 corrupted: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4883/4883 [00:00<?, ?it/s]
[34m[1mtrain: [39m[22mWARNING: Ignoring corrupted image and/or label /opt/ml/detection/yolov5/dataset/images/train/4041.jpg: duplicate labels
Plotting labels...
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_102508_1070936377>
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "train.py", line 620, in <module>
    main(opt)
  File "train.py", line 517, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 231, in train
    plot_labels(labels, names, save_dir)
  File "/opt/ml/detection/yolov5/utils/plots.py", line 310, in plot_labels
    ax = plt.subplots(2, 2, figsize=(8, 8), tight_layout=True)[1].ravel()
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 471, in wrapper
    return func(*args, **kwargs)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1440, in subplots
    axs = fig.subplots(nrows=nrows, ncols=ncols, sharex=sharex, sharey=sharey,
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 471, in wrapper
    return func(*args, **kwargs)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/figure.py", line 911, in subplots
    axs = gs.subplots(sharex=sharex, sharey=sharey, squeeze=squeeze,
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/gridspec.py", line 307, in subplots
    axarr[row, col] = figure.add_subplot(
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/figure.py", line 784, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axes/_subplots.py", line 36, in __init__
    self._axes_class.__init__(self, fig, [0, 0, 1, 1], **kwargs)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 471, in wrapper
    return func(*args, **kwargs)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 634, in __init__
    self.cla()
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 1245, in cla
    self.grid(False)  # Disable grid on init to use rcParameter
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 3064, in grid
    self.xaxis.grid(b, which=which, **kwargs)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axis.py", line 1433, in grid
    self.set_tick_params(which='major', **gridkw)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axis.py", line 856, in set_tick_params
    for tick in self.majorTicks:
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axis.py", line 608, in __get__
    instance.majorTicks.append(tick)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axis.py", line 607, in __get__
    tick = instance._get_tick(major=True)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axis.py", line 2059, in _get_tick
    return XTick(self.axes, 0, major=major, **tick_kw)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axis.py", line 420, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/axis.py", line 169, in __init__
    self.gridline.get_path()._interpolation_steps = \
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/lines.py", line 1022, in get_path
    self.recache()
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/matplotlib/lines.py", line 672, in recache
    self._xy = np.column_stack(np.broadcast_arrays(x, y)).astype(float)
  File "<__array_function__ internals>", line 5, in column_stack
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/numpy/lib/shape_base.py", line 656, in column_stack
    return _nx.concatenate(arrays, 1)
  File "<__array_function__ internals>", line 5, in concatenate
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 102504) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 28, in _pin_memory_loop
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/opt/conda/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/opt/ml/detection/yolov5/yolo_venv/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 289, in rebuild_storage_fd
    fd = df.detach()
  File "/opt/conda/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/opt/conda/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/opt/conda/lib/python3.8/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused